In [1]:
from efficient_apriori import apriori
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train_pre.csv')

In [3]:
df.iloc[0]

fecha_dato                      2015-01-28
ncodpers                           1375586
ind_empleado                             N
sexo                                     H
age                                     35
fecha_alta                      2015-01-12
ind_nuevo                                0
antiguedad                               6
indrel                                   1
indrel_1mes                              1
tiprel_1mes                              A
indresi                                  S
indext                                   N
canal_entrada                          KHL
indfall                                  N
nomprov                             MALAGA
ind_actividad_cliente                    1
renta                              87218.1
segmento                 02 - PARTICULARES
ind_ahor_fin_ult1                        0
ind_aval_fin_ult1                        0
ind_cco_fin_ult1                         1
ind_cder_fin_ult1                        0
ind_cno_fin

In [4]:
df_values = df.values

In [5]:
df_values.shape

(10795600, 43)

In [6]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)
df

fecha_dato  ncodpers ind_empleado sexo   age  fecha_alta  ind_nuevo  \
0         2015-01-28   1375586            N    H  35.0  2015-01-12        0.0   
1         2015-01-28   1050611            N    V  23.0  2012-08-10        0.0   
2         2015-01-28   1050612            N    V  23.0  2012-08-10        0.0   
3         2015-01-28   1050613            N    H  22.0  2012-08-10        0.0   
4         2015-01-28   1050615            N    H  23.0  2012-08-10        0.0   
...              ...       ...          ...  ...   ...         ...        ...   
10795595  2016-05-28   1166767            N    V  25.0  2013-08-14        0.0   
10795596  2016-05-28   1166766            N    V  25.0  2013-08-14        0.0   
10795597  2016-05-28   1166765            N    V  22.0  2013-08-14        0.0   
10795598  2016-05-28   1166764            N    V  23.0  2013-08-14        0.0   
10795599  2016-05-28   1166789            N    H  22.0  2013-08-14        0.0   

          antiguedad  indrel  indrel_1mes tiprel_1mes indresi indext  \
0                  6     1.0          1.0           A       S      N   
1                 35     1.0          1.0           I       S      S   
2                 35     1.0          1.0           I       S      N   
3                 35     1.0          1.0           I       S      N   
4                 35     1.0          1.0           I       S      N   
...              ...     ...          ...         ...     ...    ...   
10795595          33     1.0          1.0           I       S      S   
10795596          33     1.0          1.0           I       S      N   
10795597          33     1.0          1.0           I       S      N   
10795598          33     1.0          1.0           I       S      N   
10795599          33     1.0          1.0           I       S      N   

         canal_entrada indfall      nomprov  ind_actividad_cliente      renta  \
0                  KHL       N       MALAGA                    1.0   87218.10   
1                  KHE       N  CIUDAD REAL                    0.0   35548.74   
2                  KHE       N  CIUDAD REAL                    0.0  122179.11   
3                  KHD       N     ZARAGOZA                    0.0  119775.54   
4                  KHE       N       TOLEDO                    0.0   22220.04   
...                ...     ...          ...                    ...        ...   
10795595           KHE       N     ZARAGOZA                    0.0   73134.81   
10795596           KHE       N     ZARAGOZA                    0.0   50945.25   
10795597           KHE       N     ZARAGOZA                    0.0   43912.17   
10795598           KHE       N    RIOJA, LA                    0.0   23334.99   
10795599           KHE       N     ZARAGOZA                    0.0  199592.82   

                    segmento  ind_ahor_fin_ult1  ind_aval_fin_ult1  \
0          02 - PARTICULARES                  0                  0   
1         03 - UNIVERSITARIO                  0                  0   
2         03 - UNIVERSITARIO                  0                  0   
3         03 - UNIVERSITARIO                  0                  0   
4         03 - UNIVERSITARIO                  0                  0   
...                      ...                ...                ...   
10795595  03 - UNIVERSITARIO                  0                  0   
10795596  03 - UNIVERSITARIO                  0                  0   
10795597  03 - UNIVERSITARIO                  0                  0   
10795598  03 - UNIVERSITARIO                  0                  0   
10795599  03 - UNIVERSITARIO                  0                  0   

          ind_cco_fin_ult1  ind_cder_fin_ult1  ind_cno_fin_ult1  \
0                        1                  0                 0   
1                        1                  0                 0   
2                        1                  0                 0   
3                        0                  0                 0   
4                      

In [7]:
pd.reset_option('^display.', silent=True)

In [8]:
df_values

array([['2015-01-28', 1375586, 'N', ..., 0.0, 0.0, 0],
       ['2015-01-28', 1050611, 'N', ..., 0.0, 0.0, 0],
       ['2015-01-28', 1050612, 'N', ..., 0.0, 0.0, 0],
       ...,
       ['2016-05-28', 1166765, 'N', ..., 0.0, 0.0, 0],
       ['2016-05-28', 1166764, 'N', ..., 0.0, 0.0, 0],
       ['2016-05-28', 1166789, 'N', ..., 0.0, 0.0, 0]], dtype=object)

In [9]:
df.dtypes

fecha_dato                object
ncodpers                   int64
ind_empleado              object
sexo                      object
age                      float64
fecha_alta                object
ind_nuevo                float64
antiguedad                 int64
indrel                   float64
indrel_1mes              float64
tiprel_1mes               object
indresi                   object
indext                    object
canal_entrada             object
indfall                   object
nomprov                   object
ind_actividad_cliente    float64
renta                    float64
segmento                  object
ind_ahor_fin_ult1          int64
ind_aval_fin_ult1          int64
ind_cco_fin_ult1           int64
ind_cder_fin_ult1          int64
ind_cno_fin_ult1           int64
ind_ctju_fin_ult1          int64
ind_ctma_fin_ult1          int64
ind_ctop_fin_ult1          int64
ind_ctpp_fin_ult1          int64
ind_deco_fin_ult1          int64
ind_deme_fin_ult1          int64
ind_dela_f

In [10]:
transaction = df.iloc[:, 19:].values

In [11]:
print(transaction, transaction.shape)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]] (10795600, 24)


In [30]:
a = [2,3]
for k in range(len(a)):
    a[k] = str(a[k]) + '-' + df.iloc[0, 0]

In [31]:
a

['2-2015-01-28', '3-2015-01-28']

In [48]:
encode = list()

for i, j in enumerate(transaction[0:1029998]):
    ad = np.where(j == 1.0)[0]
    new_list = list()
    for k in range(len(ad)):
        new_list.append(str(ad[k]) + '-' + df.iloc[i, 0])
    encode.append(new_list)

In [47]:
sum(df.iloc[:, 0] == '2015-01-28') + sum(df.iloc[:, 0] == '2015-02-28')

1029998

In [49]:
print(encode[1000000])

['2-2015-02-28']


In [51]:
itemsets, rules = apriori(encode, min_support=0.005, min_confidence=1)
                      
for rule in rules:
    print("{}\n".format(rule))

{21-2015-01-28} -> {22-2015-01-28} (conf: 1.000, supp: 0.033, lift: 26.951, conv: 962895073.583)

{21-2015-02-28} -> {22-2015-02-28} (conf: 1.000, supp: 0.035, lift: 26.086, conv: 961665944.982)

{21-2015-01-28, 23-2015-01-28} -> {22-2015-01-28} (conf: 1.000, supp: 0.027, lift: 26.951, conv: 962895073.583)

{21-2015-01-28, 4-2015-01-28} -> {22-2015-01-28} (conf: 1.000, supp: 0.032, lift: 26.951, conv: 962895073.583)

{12-2015-01-28, 21-2015-01-28} -> {22-2015-01-28} (conf: 1.000, supp: 0.013, lift: 26.951, conv: 962895073.583)

{18-2015-01-28, 21-2015-01-28} -> {22-2015-01-28} (conf: 1.000, supp: 0.013, lift: 26.951, conv: 962895073.583)

{17-2015-01-28, 21-2015-01-28} -> {22-2015-01-28} (conf: 1.000, supp: 0.011, lift: 26.951, conv: 962895073.583)

{21-2015-01-28, 8-2015-01-28} -> {22-2015-01-28} (conf: 1.000, supp: 0.007, lift: 26.951, conv: 962895073.583)

{21-2015-01-28, 7-2015-01-28} -> {22-2015-01-28} (conf: 1.000, supp: 0.006, lift: 26.951, conv: 962895073.583)

{18-2015-02-28, 

In [17]:
encode2 = list()

for i, j in enumerate(transaction):
    ad = np.where(j == 1.0)[0]
    if 2 not in ad:
       continue
    else:
        encode2.append(list(np.where(j == 1.0)[0]))
print(encode2)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [24]:
itemsets2, rules2 = apriori(encode2, min_support=0.05, min_confidence=1)
                      
for rule in rules2:
    print("{}\n".format(rule))

{23} -> {2} (conf: 1.000, supp: 0.118, lift: 1.000, conv: 0.000)

{12} -> {2} (conf: 1.000, supp: 0.073, lift: 1.000, conv: 0.000)

{7} -> {2} (conf: 1.000, supp: 0.139, lift: 1.000, conv: 0.000)



In [29]:
df["tot_products"] = df.loc[:,"ind_ahor_fin_ult1":"ind_recibo_ult1"].sum(axis=1)
df["tot_products"]   = pd.to_numeric(df["tot_products"], errors="coerce") 

In [30]:
df

fecha_dato  ncodpers ind_empleado sexo   age  fecha_alta  ind_nuevo  \
0         2015-01-28   1375586            N    H  35.0  2015-01-12        0.0   
1         2015-01-28   1050611            N    V  23.0  2012-08-10        0.0   
2         2015-01-28   1050612            N    V  23.0  2012-08-10        0.0   
3         2015-01-28   1050613            N    H  22.0  2012-08-10        0.0   
4         2015-01-28   1050615            N    H  23.0  2012-08-10        0.0   
...              ...       ...          ...  ...   ...         ...        ...   
10795595  2016-05-28   1166767            N    V  25.0  2013-08-14        0.0   
10795596  2016-05-28   1166766            N    V  25.0  2013-08-14        0.0   
10795597  2016-05-28   1166765            N    V  22.0  2013-08-14        0.0   
10795598  2016-05-28   1166764            N    V  23.0  2013-08-14        0.0   
10795599  2016-05-28   1166789            N    H  22.0  2013-08-14        0.0   

          antiguedad  indrel  indrel_1mes  ... ind_plan_fin_ult1  \
0                  6     1.0          1.0  ...                 0   
1                 35     1.0          1.0  ...                 0   
2                 35     1.0          1.0  ...                 0   
3                 35     1.0          1.0  ...                 0   
4                 35     1.0          1.0  ...                 0   
...              ...     ...          ...  ...               ...   
10795595          33     1.0          1.0  ...                 0   
10795596          33     1.0          1.0  ...                 0   
10795597          33     1.0          1.0  ...                 0   
10795598          33     1.0          1.0  ...                 0   
10795599          33     1.0          1.0  ...                 0   

         ind_pres_fin_ult1 ind_reca_fin_ult1 ind_tjcr_fin_ult1  \
0                        0                 0                 0   
1                        0                 0                 0   
2                        0                 0                 0   
3                        0                 0                 0   
4                        0                 0                 0   
...                    ...               ...               ...   
10795595                 0                 0                 0   
10795596                 0                 0                 0   
10795597                 0                 0                 0   
10795598                 0                 0                 0   
10795599                 0                 0                 0   

         ind_valo_fin_ult1 ind_viv_fin_ult1  ind_nomina_ult1  \
0                        0                0              0.0   
1                        0                0              0.0   
2                        0                0              0.0   
3                        0                0              0.0   
4                        0                0              0.0   
...                    ...              ...              ...   
10795595                 0                0              0.0   
10795596                 0                0              0.0   
10795597                 0                0              0.0   
10795598                 0                0              0.0   
10795599                 0                0              0.0   

          ind_nom_pens_ult1 ind_recibo_ult1  tot_products  
0                       0.0               0           1.0  
1                       0.0               0           1.0  
2                       0.0               0           1.0  
3                       0.0               0           1.0  
4                       0.0               0           1.0  
...                     ...             ...           ...  
10795595                0.0               0           1.0  
10795596                0.0               0           1.0  
10795597                0.0               0           1.0  
10795598                0.0               0           1.0 

In [33]:
df_a = df.loc[:, ["tot_products"]].join(df.loc[:, "ind_ahor_fin_ult1":"ind_recibo_ult1"]) 
df_a = df_a.groupby("tot_products").agg("sum")
df_a = df_a.T

df_a

tot_products       0.0        1.0        2.0       3.0       4.0       5.0   \
ind_ahor_fin_ult1   0.0      256.0      210.0     267.0     239.0      96.0   
ind_aval_fin_ult1   0.0        0.0        0.0       2.0      35.0       2.0   
ind_cco_fin_ult1    0.0  4671587.0  1442301.0  522874.0  220369.0   98492.0   
ind_cder_fin_ult1   0.0      319.0      990.0     913.0     672.0     495.0   
ind_cno_fin_ult1    0.0    58461.0    73649.0  119493.0  165442.0  164134.0   
ind_ctju_fin_ult1   0.0   110686.0      704.0      94.0       2.0       0.0   
ind_ctma_fin_ult1   0.0    28178.0    33744.0   17046.0    7483.0    5109.0   
ind_ctop_fin_ult1   0.0   337285.0   613620.0  234320.0  114840.0   67761.0   
ind_ctpp_fin_ult1   0.0    75361.0   105637.0   74698.0   57738.0   51591.0   
ind_deco_fin_ult1   0.0     4705.0     7614.0    2152.0    1296.0     663.0   
ind_deme_fin_ult1   0.0      282.0     3253.0    4974.0    3920.0    2029.0   
ind_dela_fin_ult1   0.0    36747.0   120500.0  132910.0   71870.0   43342.0   
ind_ecue_fin_ult1   0.0   104456.0   201906.0  173716.0  125512.0  109107.0   
ind_fond_fin_ult1   0.0     8057.0    29484.0   46933.0   39707.0   25969.0   
ind_hip_fin_ult1    0.0     4651.0     2558.0    6867.0    6770.0    9021.0   
ind_plan_fin_ult1   0.0    14402.0     9771.0   14110.0   13564.0   12380.0   
ind_pres_fin_ult1   0.0    10790.0    10506.0    2272.0    1105.0     810.0   
ind_reca_fin_ult1   0.0    48882.0    72515.0   98157.0   88356.0   81322.0   
ind_tjcr_fin_ult1   0.0    16939.0    31281.0   69066.0   77923.0   81861.0   
ind_valo_fin_ult1   0.0    12517.0    40849.0   64697.0   47606.0   33860.0   
ind_viv_fin_ult1    0.0     5646.0     9219.0    9821.0    6338.0    3930.0   
ind_nomina_ult1     0.0        0.0     1143.0   60891.0  116073.0  128888.0   
ind_nom_pens_ult1   0.0      188.0     5804.0   69634.0  127070.0  140938.0   
ind_recibo_ult1     0.0    14322.0   381250.0  242558.0  250502.0  204040.0   

tot_products           6.0       7.0      8.0      9.0      10.0    11.0  \
ind_ahor_fin_ult1      57.0      53.0      7.0     10.0     19.0     9.0   
ind_aval_fin_ult1      34.0      40.0     73.0     55.0     32.0    17.0   
ind_cco_fin_ult1    49873.0   33745.0  23340.0  13184.0   5489.0  2266.0   
ind_cder_fin_ult1     323.0     252.0    189.0    188.0     69.0    74.0   
ind_cno_fin_ult1   152013.0  113013.0  62561.0  28262.0  10910.0  3765.0   
ind_ctju_fin_ult1       2.0       0.0      0.0      0.0      0.0     0.0   
ind_ctma_fin_ult1    3893.0    2461.0   1065.0    560.0    164.0    60.0   
ind_ctop_fin_ult1   48373.0   35617.0  22145.0  12027.0   5575.0  2149.0   
ind_ctpp_fin_ult1   47089.0   42111.0  28291.0  15608.0   6886.0  2676.0   
ind_deco_fin_ult1     474.0     339.0    285.0    206.0    120.0    37.0   
ind_deme_fin_ult1    1445.0     900.0    793.0    719.0    340.0   331.0   
ind_dela_fin_ult1   31181.0   26584.0  20677.0  12351.0   5971.0  2604.0   
ind_ecue_fin_ult1   98542.0   75147.0  46695.0  22247.0   9449.0  3608.0   
ind_fond_fin_ult1   18293.0   14879.0  13847.0   9723.0   5317.0  2491.0   
ind_hip_fin_ult1    10836.0   11758.0   9390.0   5088.0   2488.0   937.0   
ind_plan_fin_ult1   11226.0   10876.0   9348.0   7194.0   4190.0  1815.0   
ind_pres_fin_ult1     877.0     887.0    646.0    311.0    205.0    43.0   
ind_reca_fin_ult1   82334.0   73589.0  44582.0  21064.0   8488.0  3215.0   
ind_tjcr_fin_ult1   87204.0   77154.0  48120.0  23070.0   9371.0  3513.0   
ind_valo_fin_ult1   27670.0   24862.0  21264.0  12874.0   6583.0  2666.0   
ind_viv_fin_ult1     3304.0    2920.0   2456.0   1557.0    816.0   384.0   
ind_nomina_ult1    132145.0  105140.0  59798.0  27646.0  11114.0  3877.0   
ind_nom_pens_ult1  142088.0  110430.0  62611.0  28714.0  11374.0  3981.0   
ind_recibo_ult1    167726.0  119404.0  65785.0  29718.0  11540.0  3999.0   

tot_products         12.0   13.0  14.0  15.0  
ind_ahor_fin_ult1     7.0    5.0  14.0   0.0  
ind_aval_fin_ult1     4.0    

In [32]:
# percentage of each product contribution of those customers who only purchased one product in any month
a = df_a[1]
b = df_a[1].sum()
c = (a/b)*100
c = c.sort_values(ascending=False)
c

ind_cco_fin_ult1     83.950127
ind_ctop_fin_ult1     6.061135
ind_ctju_fin_ult1     1.989068
ind_ecue_fin_ult1     1.877113
ind_ctpp_fin_ult1     1.354265
ind_cno_fin_ult1      1.050566
ind_reca_fin_ult1     0.878427
ind_dela_fin_ult1     0.660357
ind_ctma_fin_ult1     0.506369
ind_tjcr_fin_ult1     0.304400
ind_plan_fin_ult1     0.258809
ind_recibo_ult1       0.257372
ind_valo_fin_ult1     0.224935
ind_pres_fin_ult1     0.193900
ind_fond_fin_ult1     0.144787
ind_viv_fin_ult1      0.101461
ind_deco_fin_ult1     0.084551
ind_hip_fin_ult1      0.083580
ind_cder_fin_ult1     0.005733
ind_deme_fin_ult1     0.005068
ind_ahor_fin_ult1     0.004600
ind_nom_pens_ult1     0.003378
ind_nomina_ult1       0.000000
ind_aval_fin_ult1     0.000000
Name: 1.0, dtype: float64

In [34]:
# percentage of each product contribution of those customers who purchased two products in any month
a = df_a[2]
b = df_a[2].sum()
c = (a/b)*100
c = c.sort_values(ascending=False)
c

ind_cco_fin_ult1     45.092931
ind_ctop_fin_ult1    19.184570
ind_recibo_ult1      11.919620
ind_ecue_fin_ult1     6.312506
ind_dela_fin_ult1     3.767382
ind_ctpp_fin_ult1     3.302696
ind_cno_fin_ult1      2.302605
ind_reca_fin_ult1     2.267151
ind_valo_fin_ult1     1.277127
ind_ctma_fin_ult1     1.054992
ind_tjcr_fin_ult1     0.977987
ind_fond_fin_ult1     0.921805
ind_pres_fin_ult1     0.328466
ind_plan_fin_ult1     0.305486
ind_viv_fin_ult1      0.288228
ind_deco_fin_ult1     0.238048
ind_nom_pens_ult1     0.181460
ind_deme_fin_ult1     0.101704
ind_hip_fin_ult1      0.079975
ind_nomina_ult1       0.035735
ind_cder_fin_ult1     0.030952
ind_ctju_fin_ult1     0.022010
ind_ahor_fin_ult1     0.006566
ind_aval_fin_ult1     0.000000
Name: 2.0, dtype: float64

In [35]:
# percentage of each product contribution of those customers who purchased two products in any month
a = df_a[3]
b = df_a[3].sum()
c = (a/b)*100
c = c.sort_values(ascending=False)
c

ind_cco_fin_ult1     26.562525
ind_recibo_ult1      12.322190
ind_ctop_fin_ult1    11.903691
ind_ecue_fin_ult1     8.824947
ind_dela_fin_ult1     6.751962
ind_cno_fin_ult1      6.070364
ind_reca_fin_ult1     4.986474
ind_ctpp_fin_ult1     3.794733
ind_nom_pens_ult1     3.537477
ind_tjcr_fin_ult1     3.508622
ind_valo_fin_ult1     3.286673
ind_nomina_ult1       3.093324
ind_fond_fin_ult1     2.384244
ind_ctma_fin_ult1     0.865954
ind_plan_fin_ult1     0.716802
ind_viv_fin_ult1      0.498917
ind_hip_fin_ult1      0.348851
ind_deme_fin_ult1     0.252684
ind_pres_fin_ult1     0.115420
ind_deco_fin_ult1     0.109324
ind_cder_fin_ult1     0.046381
ind_ahor_fin_ult1     0.013564
ind_ctju_fin_ult1     0.004775
ind_aval_fin_ult1     0.000102
Name: 3.0, dtype: float64

In [36]:
# percentage of each product contribution of those customers who purchased two products in any month
a = df_a[4]
b = df_a[4].sum()
c = (a/b)*100
c = c.sort_values(ascending=False)
c

ind_recibo_ult1      16.219685
ind_cco_fin_ult1     14.268611
ind_cno_fin_ult1     10.712158
ind_nom_pens_ult1     8.227620
ind_ecue_fin_ult1     8.126742
ind_nomina_ult1       7.515579
ind_ctop_fin_ult1     7.435743
ind_reca_fin_ult1     5.720938
ind_tjcr_fin_ult1     5.045415
ind_dela_fin_ult1     4.653491
ind_ctpp_fin_ult1     3.738462
ind_valo_fin_ult1     3.082428
ind_fond_fin_ult1     2.570978
ind_plan_fin_ult1     0.878252
ind_ctma_fin_ult1     0.484515
ind_hip_fin_ult1      0.438349
ind_viv_fin_ult1      0.410377
ind_deme_fin_ult1     0.253815
ind_deco_fin_ult1     0.083914
ind_pres_fin_ult1     0.071547
ind_cder_fin_ult1     0.043511
ind_ahor_fin_ult1     0.015475
ind_aval_fin_ult1     0.002266
ind_ctju_fin_ult1     0.000129
Name: 4.0, dtype: float64

In [42]:
encode3 = list()

for i, j in enumerate(transaction):
    ad = np.where(j == 1.0)[0]
    if len(ad) == 3:
       encode3.append(ad)
print(encode3)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [43]:
itemsets3, rules3 = apriori(encode3, min_support=0.05, min_confidence=1)
                      
for rule in rules3:
    print("{}\n".format(rule))

{21} -> {22} (conf: 1.000, supp: 0.093, lift: 9.423, conv: 893875684.861)

{4, 21} -> {22} (conf: 1.000, supp: 0.084, lift: 9.423, conv: 893875684.861)



In [45]:
encode4 = list()

for i, j in enumerate(transaction):
    ad = np.where(j == 1.0)[0]
    if len(ad) == 4:
        encode4.append(ad)
print(encode4)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [46]:
itemsets4, rules4 = apriori(encode4, min_support=0.05, min_confidence=1)
                      
for rule in rules4:
    print("{}\n".format(rule))

{21} -> {22} (conf: 1.000, supp: 0.301, lift: 3.039, conv: 670895189.947)

{4, 21} -> {22} (conf: 1.000, supp: 0.282, lift: 3.039, conv: 670895189.947)

{21, 23} -> {22} (conf: 1.000, supp: 0.214, lift: 3.039, conv: 670895189.947)

{4, 21, 23} -> {22} (conf: 1.000, supp: 0.203, lift: 3.039, conv: 670895189.947)



In [47]:
encode5 = list()

for i, j in enumerate(transaction):
    ad = np.where(j == 1.0)[0]
    if len(ad) == 5:
        encode5.append(ad)
print(encode5)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [49]:
itemsets5, rules5 = apriori(encode5, min_support=0.1, min_confidence=1)
                      
for rule in rules5:
    print("{}\n".format(rule))

{21} -> {22} (conf: 1.000, supp: 0.509, lift: 1.796, conv: 443302471.086)

{4, 21} -> {22} (conf: 1.000, supp: 0.478, lift: 1.796, conv: 443302471.086)

{12, 21} -> {22} (conf: 1.000, supp: 0.174, lift: 1.796, conv: 443302471.086)

{21, 23} -> {22} (conf: 1.000, supp: 0.420, lift: 1.796, conv: 443302471.086)

{18, 21} -> {22} (conf: 1.000, supp: 0.110, lift: 1.796, conv: 443302471.086)

{4, 12, 21} -> {22} (conf: 1.000, supp: 0.163, lift: 1.796, conv: 443302471.086)

{4, 21, 23} -> {22} (conf: 1.000, supp: 0.397, lift: 1.796, conv: 443302471.086)

{12, 21, 23} -> {22} (conf: 1.000, supp: 0.131, lift: 1.796, conv: 443302471.086)

{4, 18, 21} -> {22} (conf: 1.000, supp: 0.102, lift: 1.796, conv: 443302471.086)

{4, 12, 21, 23} -> {22} (conf: 1.000, supp: 0.124, lift: 1.796, conv: 443302471.086)

